print("###################################################### ")
print(" ###                                                   ")
print(" ###  ##   #######   #########   #########   ###   ### ")
print(" #######  ###   ###   ###   ###   ###   ###  ###   ### ")
print(" ###  ##  ########    ###         ###         ######## ")
print(" ###      ###         ###         ###              ### ")
print("#####      #######    ###         ###        ########\n")

print("Tuple 1 : ")
data = (13,15,11,10,25,27,23,27,34,37,36,36,40,42,41,40)
a = (data[0:4])
b = (data[4:8])
c = (data[8:12])
d = (data[12:16])
print((a,b,c,d))
print("\nRata-rata nilai pada masing-masing tuple adalah : ")
print([sum(a)/float(len(a)),sum(b)/float(len(b)),sum(c)/float(len(c)),sum(d)/float(len(d))])